### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Shinyaigeek** [Shinyaigeek/shinyaigeek.dev#30]
## DX
- [ ] CI/CD
- [ ] Issue/PR Template
- [ ] linter with husky
- [ ] light house CI
- [ ] renovate

## style
- [ ] tag
- [ ] button
- [x] syntax highlight

## perf
- [x] http2
- [ ] http header tuning
- [x] cloudflare workers
- [x] avoid using express

## other
- [x] api to return xml
